#include "MapUiVisualDetector.h"

#include "../Coordinate/HudLayout.h"
#include "MapCompassTemplateData.h"

#include <algorithm>
#include <array>
#include <cmath>
#include <cstdint>
#include <opencv2/imgcodecs.hpp>
#include <opencv2/imgproc.hpp>
#include <string>
#include <utility>
#include <vector>

namespace {
// The box decides where the widget is; the frame's own size decides the scale. A frame that lags a
// window resize is mapped with its own dimensions, which is what its pixels were drawn for.
cv::Rect ScaleCrop(const cv::Mat& snapshot, const hud::Box& box) {
    if (snapshot.empty()) return {};
    const cv::Rect requested = hud::MapBox(hud::Layout::For(snapshot.cols, snapshot.rows), box);
    return requested & cv::Rect(0, 0, snapshot.cols, snapshot.rows);
}

// ---------------------------------------------------------------------------------------------
// Embedded big-map compass template.
//
// The widget is a fixed opaque HUD graphic drawn in two flat colours - a gold ring, points, ticks and
// centre disc plus a cream-white needle - over whatever the game paints behind it.  The reference is
// therefore stored as a per-pixel class map (0 other, 1 gold, 2 bright, 3 dark) and only the gold and
// bright pixels take part in the comparison, so the background costs nothing.
//
// Measured on the shipped captures (Tests/MapUi, generated by scripts/New-MapCompassTemplate.ps1) and on
// the real non-16:9 sessions: the widget scores 80-100% agreement once the map has settled, and every
// frame without it - ordinary gameplay, the marker dialog, the hand-holding panel that covers the compass
// - scores at most 3%.  Alignment peaks at offset (0,0) on the 16:9 and on the 16:10 client alike, so the
// radius below is tolerance for the pixel or two a client's rounding can differ by, not a search for the
// widget: the reference capture's box displaced by the old per-axis model's error (5px and up) is still
// rejected, which MapControllerUiTests.h asserts.
//
// The map is compiled in rather than shipped as an asset because RuntimeFeatureRepository::Load treats a
// missing FeaturesDatas file as a resource-load failure, and the MapTest delivery tree carries no loose
// feature files at all.
constexpr int kTemplateSearchRadius = 2;
constexpr double kTemplateMinAgreement = 0.65;
constexpr double kTemplateMinCoverage = 0.40;

enum class CompassPixelClass : unsigned char { Other = 0, Gold = 1, Bright = 2, Dark = 3 };

CompassPixelClass ClassifyCompassPixel(const cv::Vec3b& pixel) {
    const int blue = pixel[0];
    const int green = pixel[1];
    const int red = pixel[2];
    if (red > 120 && green > 90 && blue < 100 && red - blue > 50) return CompassPixelClass::Gold;
    if (red > 200 && green > 200 && blue > 190) return CompassPixelClass::Bright;
    if ((std::max)({red, green, blue}) <= 130) return CompassPixelClass::Dark;
    return CompassPixelClass::Other;
}

std::vector<unsigned char> DecodeBase64(const char* text, std::size_t length) {
    const std::array<signed char, 256>& table = [] {
        std::array<signed char, 256> values{};
        values.fill(-1);
        const std::string alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
        for (std::size_t i = 0; i < alphabet.size(); ++i) {
            values[static_cast<unsigned char>(alphabet[i])] = static_cast<signed char>(i);
        }
        return values;
    }();
    std::vector<unsigned char> bytes;
    bytes.reserve(length / 4 * 3);
    unsigned int accumulator = 0;
    int bits = 0;
    for (std::size_t i = 0; i < length; ++i) {
        const signed char value = table[static_cast<unsigned char>(text[i])];
        if (value < 0) continue;  // Padding and line breaks end the group without contributing bits.
        accumulator = (accumulator << 6) | static_cast<unsigned int>(value);
        bits += 6;
        if (bits >= 8) {
            bits -= 8;
            bytes.push_back(static_cast<unsigned char>((accumulator >> bits) & 0xFF));
        }
    }
    return bytes;
}

struct CompassTemplateReference {
    bool available = false;
    const char* reason = "unloaded";
    int decodedBytes = 0;
    std::vector<unsigned char> classes;            // kWidth * kHeight, one class per pixel
    std::vector<std::pair<short, short>> mask;     // gold and bright pixels only
};

CompassTemplateReference BuildCompassTemplateReference() {
    CompassTemplateReference reference;
    const auto bytes = DecodeBase64(map_compass_template::kClassMapBase64,
        sizeof(map_compass_template::kClassMapBase64) - 1);
    reference.decodedBytes = static_cast<int>(bytes.size());
    if (bytes.empty()) {
        reference.reason = "base64-empty";
        return reference;
    }
    // Two bits per pixel, four pixels per byte, lowest bits first - no image codec in the path, so no
    // palette or colour management can reinterpret the classes.
    const std::size_t pixels = static_cast<std::size_t>(map_compass_template::kWidth) * map_compass_template::kHeight;
    if (bytes.size() != static_cast<std::size_t>(map_compass_template::kPackedBytes) ||
        bytes.size() * 4 < pixels) {
        reference.reason = "size-mismatch";
        return reference;
    }
    reference.classes.resize(pixels);
    for (std::size_t index = 0; index < pixels; ++index) {
        const auto value = static_cast<unsigned char>((bytes[index >> 2] >> ((index & 3) * 2)) & 0x03);
        reference.classes[index] = value;
        if (value == static_cast<unsigned char>(CompassPixelClass::Gold) ||
            value == static_cast<unsigned char>(CompassPixelClass::Bright)) {
            reference.mask.emplace_back(static_cast<short>(index % map_compass_template::kWidth),
                static_cast<short>(index / map_compass_template::kWidth));
        }
    }
    // A palette that decoded differently from the generated map must not be trusted at all.
    if (static_cast<int>(reference.mask.size()) != map_compass_template::kMaskPixels) {
        reference.reason = "mask-mismatch";
        reference.classes.clear();
        reference.mask.clear();
        return reference;
    }
    reference.available = true;
    reference.reason = "ok";
    return reference;
}

const CompassTemplateReference& CompassTemplate() {
    static const CompassTemplateReference reference = BuildCompassTemplateReference();
    return reference;
}

struct CompassTemplateVerdict {
    bool available = false;
    bool verified = false;
    double agreement = 0.0;
    double coverage = 0.0;
};

// Compares the template against the layout box inside `bgr`, so the template's own coordinates are
// scaled onto whatever size the live client produced.
CompassTemplateVerdict VerifyCompassTemplate(const cv::Mat& bgr, const cv::Rect& box) {
    CompassTemplateVerdict verdict;
    const auto& reference = CompassTemplate();
    verdict.available = reference.available;
    if (!reference.available || bgr.empty() || bgr.type() != CV_8UC3 || box.width <= 0 || box.height <= 0 ||
        (box & cv::Rect(0, 0, bgr.cols, bgr.rows)) != box) {
        return verdict;
    }
    const double maskSize = static_cast<double>(reference.mask.size());
    for (int offsetY = -kTemplateSearchRadius; offsetY <= kTemplateSearchRadius; ++offsetY) {
        for (int offsetX = -kTemplateSearchRadius; offsetX <= kTemplateSearchRadius; ++offsetX) {
            int matched = 0;
            int evaluated = 0;
            for (const auto& position : reference.mask) {
                // This is a translation search: the template's own pixel (position) is looked for at the
                // offset sample point, so the class it is compared against must stay the unshifted one.
                // Shifting the class along with the sample point would compare the template to itself and
                // measure nothing (that bug scored the reference capture 0.49 where a real match is 0.95).
                const int sampleX = position.first + offsetX;
                const int sampleY = position.second + offsetY;
                // The offset is applied in template space before scaling - where the measured peak lives.
                const int x = box.x + static_cast<int>(static_cast<double>(sampleX) * box.width /
                    map_compass_template::kWidth);
                const int y = box.y + static_cast<int>(static_cast<double>(sampleY) * box.height /
                    map_compass_template::kHeight);
                if (x < 0 || y < 0 || x >= bgr.cols || y >= bgr.rows) continue;
                const auto pixelClass = ClassifyCompassPixel(bgr.at<cv::Vec3b>(y, x));
                // An anti-aliased or background pixel is no evidence either way, so only a pixel that
                // classified clearly counts. That is what keeps a downscaled capture comparable.
                if (pixelClass == CompassPixelClass::Other) continue;
                ++evaluated;
                if (static_cast<unsigned char>(pixelClass) == reference.classes[
                    static_cast<std::size_t>(position.second) * map_compass_template::kWidth + position.first]) {
                    ++matched;
                }
            }
            const double coverage = evaluated / maskSize;
            if (coverage < kTemplateMinCoverage) continue;
            const double agreement = matched / static_cast<double>((std::max)(1, evaluated));
            if (agreement > verdict.agreement) {
                verdict.agreement = agreement;
                verdict.coverage = coverage;
            }
        }
    }
    verdict.verified = verdict.agreement >= kTemplateMinAgreement;
    return verdict;
}
}  // namespace

MapCompassDetection MapUiVisualDetector::DetectBigMapCompass(const cv::Mat& snapshot, const RECT& clientRect) {
    MapCompassDetection result;
    // The crop admits the complete compass but excludes the gameplay player's yellow minimap arrow at
    // the right edge.
    const cv::Rect crop = ScaleCrop(snapshot, hud::kBigMapCompass);
    if (crop.empty() || snapshot.channels() < 3) return result;

    cv::Mat bgr;
    if (snapshot.channels() == 3) bgr = snapshot;
    else if (snapshot.channels() == 4) cv::cvtColor(snapshot, bgr, cv::COLOR_BGRA2BGR);
    else return result;
    const cv::Mat compass = bgr(crop);
    result.cropPixels = compass.rows * compass.cols;
    for (int row = 0; row < compass.rows; ++row) {
        for (int column = 0; column < compass.cols; ++column) {
            const cv::Vec3b pixel = compass.at<cv::Vec3b>(row, column);
            const int blue = pixel[0];
            const int green = pixel[1];
            const int red = pixel[2];
            if (red > 120 && green > 90 && blue < 100 && red - blue > 50) {
                ++result.goldPixels;
            }
        }
    }

    // The reference map has roughly 8% gold pixels in this crop; gameplay
    // samples have none.  Three percent keeps room for capture scaling and
    // anti-aliasing while remaining well below the observed map signature.
    const bool colourVisible = result.cropPixels > 0 && result.goldPixels * 100 >= result.cropPixels * 3;

    // Three percent only says "there is gold in this box".  The minimap sits underneath the same box and
    // a panel can paint its own gold emblem on it, so the widget itself is what the template decides.
    // Zero gold cannot reach the agreement floor - the gold classes are more than half the mask - so it
    // is also a free early out.
    if (result.goldPixels > 0) {
        const auto verdict = VerifyCompassTemplate(bgr, crop);
        result.templateAvailable = verdict.available;
        result.templateVerified = verdict.verified;
        result.templateAgreement = verdict.agreement;
        result.templateCoverage = verdict.coverage;
    }
    // A reference that failed to decode must not turn the probe off entirely.
    result.visible = result.templateAvailable ? result.templateVerified : colourVisible;
    return result;
}

// The region-switch panel: the stack of large light-grey region buttons the open list paints where
// the map used to be readable. One statistic decides it, because the widget itself is a flat
// neutral grey and almost nothing the game draws behind it is - the six reference captures without
// the panel peak at 11.3% and the panel's own box reads 69.2%.
//
// Deliberately NOT a template. The buttons carry the region names, so their pixels change with the
// player's progress and with the language; only the plate underneath them is constant, and a plate
// is what a colour fraction measures directly.
namespace {
constexpr int kPanelNeutralChannels = 16;   // max - min per pixel: "grey" rather than tinted
constexpr int kPanelNeutralLow = 165;       // the button plates measure 174..196 per channel
constexpr int kPanelNeutralHigh = 245;      // below plain white, so snow stays out of it
constexpr double kPanelMinNeutralFraction = 0.35;
// The plates are separated by the panel's own dark background, and a bright flat surface is not.
// Without this the fraction alone calls an untextured cloud bank a menu: an even 235-grey fill is
// 100% neutral, where the real panel reads 69% and still shows five dark rows between its buttons.
constexpr int kPanelDarkLevel = 90;
constexpr double kPanelDarkRowFraction = 0.60;
constexpr int kPanelMinDarkRows = 2;
}  // namespace

MapRegionPanelDetection MapUiVisualDetector::DetectRegionPanel(const cv::Mat& snapshot, const RECT& clientRect) {
    (void)clientRect;
    MapRegionPanelDetection result;
    const cv::Rect crop = ScaleCrop(snapshot, hud::kRegionPanelButtons);
    if (crop.empty() || snapshot.channels() < 3) return result;

    cv::Mat bgr;
    if (snapshot.channels() == 3) bgr = snapshot;
    else if (snapshot.channels() == 4) cv::cvtColor(snapshot, bgr, cv::COLOR_BGRA2BGR);
    else return result;

    const cv::Mat panel = bgr(crop);
    result.sampledPixels = panel.rows * panel.cols;
    if (result.sampledPixels <= 0) return result;

    // "Neutral light grey" as three range tests rather than a per-pixel loop: the box is 240x390
    // reference units, which is 384x624 pixels on a 2560x1440 client, and this probe runs on the
    // state thread beside the compass.
    cv::Mat channels[3];
    cv::split(panel, channels);
    cv::Mat highest, lowest;
    cv::max(channels[0], channels[1], highest);
    cv::max(highest, channels[2], highest);
    cv::min(channels[0], channels[1], lowest);
    cv::min(lowest, channels[2], lowest);
    cv::Mat spread, neutral, notTooDark, notTooBright, neutralAndLight;
    cv::subtract(highest, lowest, spread);
    cv::inRange(spread, cv::Scalar(0), cv::Scalar(kPanelNeutralChannels), neutral);
    cv::inRange(lowest, cv::Scalar(kPanelNeutralLow), cv::Scalar(255), notTooDark);
    cv::inRange(highest, cv::Scalar(0), cv::Scalar(kPanelNeutralHigh), notTooBright);
    cv::bitwise_and(neutral, notTooDark, neutralAndLight);
    cv::bitwise_and(neutralAndLight, notTooBright, neutralAndLight);
    const int neutralPixels = cv::countNonZero(neutralAndLight);
    result.neutralFraction = static_cast<double>(neutralPixels) / result.sampledPixels;

    cv::Mat dark, darkRows;
    cv::inRange(highest, cv::Scalar(0), cv::Scalar(kPanelDarkLevel), dark);
    dark /= 255;
    cv::reduce(dark, darkRows, 1, cv::REDUCE_SUM, CV_32S);
    const int darkRowThreshold = static_cast<int>(panel.cols * kPanelDarkRowFraction);
    for (int row = 0; row < darkRows.rows; ++row) {
        if (darkRows.at<int>(row, 0) >= darkRowThreshold) ++result.darkSeparatorRows;
    }

    result.visible = result.neutralFraction >= kPanelMinNeutralFraction &&
        result.darkSeparatorRows >= kPanelMinDarkRows;
    return result;
}

MapControlDetection MapUiVisualDetector::DetectBigMapControlLayout(const cv::Mat& snapshot, const RECT& clientRect) {
    MapControlDetection result;
    if (snapshot.empty() || (snapshot.channels() != 3 && snapshot.channels() != 4) ||
        snapshot.depth() != CV_8U || snapshot.cols != clientRect.right - clientRect.left ||
        snapshot.rows != clientRect.bottom - clientRect.top) return result;

    // Normalize only the narrow zoom-control strip, keeping this probe cheap
    // enough to run on the state thread. Mouse +/- and controller RT/LT use
    // the same zoom track, but have different glyphs and additional anchors.
    // The strip is the reference box scaled by the client's HUD scale, so the
    // 60x410 normalization below stays isotropic at every client size - the
    // glyph shape tests were measured on that normalization.
    const cv::Rect strip = ScaleCrop(snapshot, hud::kBigMapZoomStrip);
    if (strip.width <= 0 || strip.height <= 0 ||
        (strip & cv::Rect(0, 0, snapshot.cols, snapshot.rows)) != strip) return result;
    cv::Mat normalized;
    cv::resize(snapshot(strip), normalized, {60, 410}, 0, 0, cv::INTER_AREA);
    cv::Mat bgr;
    if (normalized.channels() == 4) cv::cvtColor(normalized, bgr, cv::COLOR_BGRA2BGR);
    else bgr = normalized;
    cv::Mat white(bgr.size(), CV_8UC1, cv::Scalar(0));
    cv::Mat pale(bgr.size(), CV_8UC1, cv::Scalar(0));
    cv::Mat dark(bgr.size(), CV_8UC1, cv::Scalar(0));
    cv::Mat gold(bgr.size(), CV_8UC1, cv::Scalar(0));
    for (int y = 0; y < bgr.rows; ++y) {
        for (int x = 0; x < bgr.cols; ++x) {
            const auto pixel = bgr.at<cv::Vec3b>(y, x);
            const int low = std::min({pixel[0], pixel[1], pixel[2]});
            const int high = std::max({pixel[0], pixel[1], pixel[2]});
            white.at<uchar>(y, x) = low >= 155 && high - low <= 65 ? 255 : 0;
            // The thin ring is translucent, unlike the bright +/- glyph.
            pale.at<uchar>(y, x) = low >= 90 && high - low <= 65 ? 255 : 0;
            dark.at<uchar>(y, x) = high <= 130 ? 255 : 0;
            gold.at<uchar>(y, x) = pixel[2] > 120 && pixel[1] > 90 && pixel[0] < 100 &&
                static_cast<int>(pixel[2]) - pixel[0] > 50 ? 255 : 0;
        }
    }
    const auto brightNear = [&white](int x, int y) {
        return cv::countNonZero(white(cv::Rect(x - 1, y - 1, 3, 3))) > 0;
    };
    const auto buttonCandidates = [&](int expectedY, bool plus) {
        std::array<bool, 60> foundX{};
        for (int y = expectedY - 6; y <= expectedY + 6; ++y) {
            for (int x = 23; x <= 35; ++x) {
                int horizontal = 0, vertical = 0, ring = 0, darkCorners = 0;
                for (int d = -5; d <= 5; ++d) {
                    horizontal += brightNear(x + d, y);
                    if (std::abs(d) >= 3) vertical += brightNear(x, y + d);
                }
                if (horizontal < 10 || (plus ? vertical < 5 : vertical > 2)) continue;
                for (int sector = 0; sector < 16; ++sector) {
                    const double angle = sector * CV_PI / 8;
                    const int ringX = x + cvRound(10 * std::cos(angle));
                    const int ringY = y + cvRound(10 * std::sin(angle));
                    ring += cv::countNonZero(pale(cv::Rect(ringX - 1, ringY - 1, 3, 3))) > 0;
                }
                for (int dx : {-4, 4}) for (int dy : {-4, 4}) {
                    darkCorners += !brightNear(x + dx, y + dy);
                }
                if (ring >= 12 && darkCorners >= 3) {
                    foundX[x] = true;
                }
            }
        }
        return foundX;
    };
    const auto plusCandidates = buttonCandidates(30, true), minusCandidates = buttonCandidates(380, false);
    // Antialiasing can admit more than one center for a thin glyph. Pair all
    // centers that satisfy the unchanged shape tests; the first scan hit is
    // not necessarily the center aligned with the other button.
    for (int upperX = 23; upperX <= 35 && !result.mouse; ++upperX) {
        if (!plusCandidates[upperX]) continue;
        for (int lowerX = 23; lowerX <= 35; ++lowerX)
            if (minusCandidates[lowerX] && std::abs(upperX - lowerX) <= 3) { result.mouse = true; break; }
    }
    if (result.mouse) { result.visible = true; return result; }

    // Controller mode replaces +/- with opaque, dark-lettered RT/LT capsules.
    // Their fill, internal lettering and paired positions distinguish them
    // from thin mouse glyphs, terrain strokes, and large white dialog panels.
    cv::Mat labels, stats, centroids;
    const int count = cv::connectedComponentsWithStats(white, labels, stats, centroids, 8, CV_32S);
    const auto bounds = [&](int component) {
        return cv::Rect(stats.at<int>(component, cv::CC_STAT_LEFT), stats.at<int>(component, cv::CC_STAT_TOP),
            stats.at<int>(component, cv::CC_STAT_WIDTH), stats.at<int>(component, cv::CC_STAT_HEIGHT));
    };
    const auto lettered = [&](int component, const cv::Rect& box, double minimumFill, int minimumDark) {
        const int area = stats.at<int>(component, cv::CC_STAT_AREA);
        const cv::Rect inner(box.x + 4, box.y + 3, box.width - 8, box.height - 6);
        return area >= box.area() * minimumFill && area <= box.area() * 0.90 &&
            cv::countNonZero(dark(inner)) >= minimumDark;
    };
    const auto trigger = [&](int expectedY, int& foundX) {
        for (int component = 1; component < count; ++component) {
            const auto box = bounds(component);
            if (box.width < 20 || box.width > 32 || box.height < 13 || box.height > 23) continue;
            const int x = box.x + box.width / 2, y = box.y + box.height / 2;
            if (x < 23 || x > 35 || std::abs(y - expectedY) > 6 || !lettered(component, box, 0.45, 15)) continue;
            foundX = x; return true;
        }
        return false;
    };
    int upperX = 0, lowerX = 0;
    const bool upper = trigger(30, upperX), lower = trigger(380, lowerX);
    result.controllerTriggerAnchors = static_cast<int>(upper) + static_cast<int>(lower);
    if (upper && lower && std::abs(upperX - lowerX) <= 3) {
        const int trackX = (upperX + lowerX) / 2;
        // The R thumbstick indicator can move with map zoom. It must remain
        // on the same track and have both gold direction arrows around it.
        for (int component = 1; component < count; ++component) {
            const auto box = bounds(component);
            if (box.width < 18 || box.width > 32 || box.height < 18 || box.height > 32) continue;
            const int x = box.x + box.width / 2, y = box.y + box.height / 2;
            if (std::abs(x - trackX) > 3 || y < 60 || y > 350 || !lettered(component, box, 0.40, 12)) continue;
            const cv::Rect above(x - 8, box.y - 12, 17, 16);
            const cv::Rect below(x - 8, box.y + box.height - 4, 17, 16);
            if (cv::countNonZero(gold(above)) >= 12 && cv::countNonZero(gold(below)) >= 12) {
                result.controllerSlider = true; break;
            }
        }
    }
    // A pair of controller prompts alone is common elsewhere in the game, so the strip must carry the
    // whole zoom control: both lettered capsules on one track plus the slider between the gold arrows.
    // The compass used to be required here as well, which rejected a map that is open with the
    // hand-holding panel covering it (Tests/MapUi/controller-cursor-assistant.png: the zoom control is
    // intact and the compass is gone).  The compass is a probe of its own now, so it is no longer a veto.
    result.controller = result.controllerTriggerAnchors == 2 && result.controllerSlider;
    result.visible = result.controller;
    return result;
}

bool MapUiVisualDetector::DetectBigMapControls(const cv::Mat& snapshot, const RECT& clientRect) {
    return DetectBigMapControlLayout(snapshot, clientRect).visible;
}

MapCompassTemplateInfo MapUiVisualDetector::CompassTemplateInfo() {
    const auto& reference = CompassTemplate();
    MapCompassTemplateInfo info;
    info.available = reference.available;
    info.width = map_compass_template::kWidth;
    info.height = map_compass_template::kHeight;
    info.maskPixels = static_cast<int>(reference.mask.size());
    info.decodedBytes = reference.decodedBytes;
    info.reason = reference.reason;
    return info;
}
