<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ResourcePackagePickerSource Condition="'$(ResourcePackagePickerSource)' == ''">../../IMao-WinUI/Helpers/ResourcePackagePicker.cs</ResourcePackagePickerSource>
    <NativeFileDialogSource Condition="'$(NativeFileDialogSource)' == ''">../../IMao-WinUI/Helpers/NativeFileDialog.cs</NativeFileDialogSource>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="$(ResourcePackagePickerSource)" Link="ResourcePackagePicker.cs" />
    <Compile Include="$(NativeFileDialogSource)" Link="NativeFileDialog.cs" />
  </ItemGroup>
</Project>
