# Generates IMao-Core/src/App/MapCompassTemplateData.h from the reference capture.
#
# The big-map compass is a fixed, opaque HUD widget: measured on four independent captures it sits in the
# same layout box at the same relative position (gold-mask bounding box 344x344 at 2560x1440, centroid
# within 2px), so a pixel-exact class comparison decides it.  The widget is drawn with two flat colours
# (gold ring/points/ticks/centre disc and a cream-white needle) over an arbitrary background, so only
# those two classes are stored as the mask; the background is whatever the game paints behind it.
#
# The class map is embedded in the binary instead of shipped as an asset because
# RuntimeFeatureRepository::Load treats a missing FeaturesDatas file as a resource-load failure, and the
# MapTest delivery tree carries no loose feature files at all.
[CmdletBinding()]
param(
    [string]$Reference = (Join-Path $PSScriptRoot '..\Tests\MapUi\black-shores-map-region-panel.png'),
    [string]$Output    = (Join-Path $PSScriptRoot '..\IMao-Core\src\App\MapCompassTemplateData.h'),
    # Reference box from HudLayout.h (hud::kBigMapCompass, 1600x900 reference units), left/top anchored.
    [double]$BoxLeft = 10, [double]$BoxTop = 52, [double]$BoxRight = 82, [double]$BoxBottom = 116,
    [int]$BrightThreshold = 200
)
$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Drawing

$referenceImage = (Resolve-Path $Reference).Path
$bitmap = [System.Drawing.Bitmap]::FromFile($referenceImage)
$captureSize = "$($bitmap.Width)x$($bitmap.Height)"
try {
    $scale = [Math]::Min($bitmap.Width / 1600.0, $bitmap.Height / 900.0)
    $x0 = [int][Math]::Round($BoxLeft * $scale);   $y0 = [int][Math]::Round($BoxTop * $scale)
    $x1 = [int][Math]::Round($BoxRight * $scale);  $y1 = [int][Math]::Round($BoxBottom * $scale)
    $width = $x1 - $x0; $height = $y1 - $y0

    # 0 = other/anti-aliased, 1 = gold, 2 = bright (needle), 3 = dark.
    $class = New-Object 'int[,]' $width, $height
    $counts = @(0, 0, 0, 0)
    for ($y = 0; $y -lt $height; $y++) {
        for ($x = 0; $x -lt $width; $x++) {
            $p = $bitmap.GetPixel($x0 + $x, $y0 + $y)
            $c = 0
            if ($p.R -gt 120 -and $p.G -gt 90 -and $p.B -lt 100 -and ($p.R - $p.B) -gt 50) { $c = 1 }
            elseif ($p.R -gt $BrightThreshold -and $p.G -gt $BrightThreshold -and $p.B -gt ($BrightThreshold - 10)) { $c = 2 }
            elseif ([Math]::Max($p.R, [Math]::Max($p.G, $p.B)) -le 130) { $c = 3 }
            $class[$x, $y] = $c
            $counts[$c]++
        }
    }
} finally { $bitmap.Dispose() }

$mask = $counts[1] + $counts[2]
if ($mask -lt 500) { throw "reference crop only produced $mask widget pixels - wrong box or wrong capture?" }

# Pack the classes two bits per pixel, four pixels per byte, low bits first.  A PNG would be smaller,
# but an indexed PNG's palette survives GDI+ and libpng differently (measured: entries came back as
# 0/51/153/255 instead of 0/85/170/255), and the whole point of this asset is that the runtime cannot
# misinterpret it.
$packed = New-Object byte[] ([int][Math]::Ceiling($width * $height / 4.0))
for ($y = 0; $y -lt $height; $y++) {
    for ($x = 0; $x -lt $width; $x++) {
        $index = $y * $width + $x
        $packed[$index -shr 2] = $packed[$index -shr 2] -bor [byte]($class[$x, $y] -shl (($index -band 3) * 2))
    }
}

$base64 = [Convert]::ToBase64String($packed)
$wrapped = for ($i = 0; $i -lt $base64.Length; $i += 96) { '    "' + $base64.Substring($i, [Math]::Min(96, $base64.Length - $i)) + '"' }

$header = @"
// Generated by scripts/New-MapCompassTemplate.ps1 from
// $(Split-Path $referenceImage -Leaf) - do not edit by hand; re-run the script after replacing the capture.
//
// The big-map compass is a fixed opaque HUD widget drawn in two flat colours over an arbitrary
// background, so the stored map holds 2 bits of class per pixel and only the gold/bright pixels form the
// mask.  Coordinates are the class map's own; MapUiVisualDetector scales them onto whatever box
// hud::kBigMapCompass resolves to on the live client.
#pragma once

namespace map_compass_template {

// Crop size the classes were measured at (hud::kBigMapCompass on a 2560x1440 client).
inline constexpr int kWidth = $width;
inline constexpr int kHeight = $height;
// 0 = other, 1 = gold, 2 = bright, 3 = dark; gold + bright pixels are the comparison mask.
inline constexpr int kMaskPixels = $mask;
inline constexpr int kGoldPixels = $($counts[1]);
inline constexpr int kBrightPixels = $($counts[2]);
inline constexpr int kPackedBytes = $($packed.Length);

// Classes packed two bits per pixel, four pixels per byte, lowest bits first.
inline constexpr char kClassMapBase64[] =
$(($wrapped -join "`n"));

}  // namespace map_compass_template
"@

Set-Content -Path (Join-Path (Split-Path $Output -Parent) (Split-Path $Output -Leaf)) -Value $header -Encoding utf8NoBOM
"reference : $referenceImage  ($captureSize capture, crop ($x0,$y0)-($x1,$y1))"
"class map : ${width}x${height}  gold=$($counts[1]) bright=$($counts[2]) dark=$($counts[3]) other=$($counts[0])  mask=$mask"
"packed    : $($packed.Length) bytes -> base64 $($base64.Length) chars"
"written   : $((Resolve-Path $Output).Path)"
