name: mirrorchyan_release

on:
  workflow_dispatch:
    inputs:
      tag:
        default: ''
        required: false
  release:
    types: [published]

jobs:
  mirrorchyan:
    if: ${{ github.repository_owner == 'kahvia-d' }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: win
            arch: x64
            filename: 'IMao-*-windows-x64.zip'

    steps:
      - uses: MirrorChyan/uploading-action@v1
        with:
          filetype: latest-release
          filename: ${{ matrix.filename }}
          mirrorchyan_rid: IMAO
          tag: ${{ inputs.tag || github.event.release.tag_name }}

          os: ${{ matrix.os }}
          arch: ${{ matrix.arch }}

          owner: kahvia-d
          repo: IMAO
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upload_token: ${{ secrets.MirrorChyanUploadToken }}
